services:
  - type: web
    name: system-project-api
    runtime: python
    pythonVersion: "3.11.4"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --timeout 120 app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
